name: Nested Greeting Workflow

on:
  workflow_dispatch:

jobs:
  run-by-os:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: "OS: ${{ matrix.os }}"
    uses: ./.github/workflows/workflow-a.yml
    with:
      os: ${{ matrix.os }}
