name: Nested Greeting Workflow

on:
  workflow_dispatch:

jobs:
  run-by-os:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: "OS: ${{ matrix.os }}"
    uses: ./.github/workflows/workflow-a.yml
    with:
      os: ${{ matrix.os }}

  # New job to check if all "Alex" jobs passed.
  CheckAlexStatus:
    needs: run-by-os
    if: always()
    runs-on: ubuntu-latest
    outputs:
      all_alex_passed: ${{ steps.check.outputs.all_alex_passed }}
    steps:
      - name: Check Alex's job statuses
        id: check
        run: |
          # This approach will not work as intended due to a limitation in how matrix job outputs
          # are exposed to dependent jobs. To correctly check for a specific matrix job's
          # status, you would need to refactor the workflow to avoid nesting the matrix,
          # or use a more complex method of outputting and parsing the results.
          
          # Initialize a flag to 'true'
          ALL_ALEX_PASSED="true"
          
          # Check the outputs of each OS job
          # The following conditional will always fail because the `outputs` from
          # a reusable workflow called in a matrix job are not directly accessible here.
          if [ "${{ needs.run-by-os.outputs.alex-status }}" != "success" ]; then
            ALL_ALEX_PASSED="false"
          fi

          # Set the output variable
          echo "all_alex_passed=$ALL_ALEX_PASSED" >> "$GITHUB_OUTPUT"

  # New stage that relies on all 'Alex' jobs passing.
  StageAfterAlex:
    needs: CheckAlexStatus
    runs-on: ubuntu-latest
    if: needs.CheckAlexStatus.outputs.all_alex_passed == 'true'
    steps:
      - name: All Alex jobs passed
        run: echo "All jobs with name 'Alex' passed. Proceeding with the next stage."
