name: Greeting Matrix

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      name:
        required: true
        type: string

jobs:
  run-by-greeting:
    strategy:
      matrix:
        greeting: [Hello, Goodbye, Goodnight, Wake up]
    name: "Greeting: ${{ matrix.greeting }}"
    uses: ./.github/workflows/workflow-c.yml
    with:
      os: ${{ inputs.os }}
      name: ${{ inputs.name }}
      greeting: ${{ matrix.greeting }}
