name: Final Message

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      name:
        required: true
        type: string
      greeting:
        required: true
        type: string

jobs:
  echo-message:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Echo the message
        run: echo "${{ inputs.greeting }}, ${{ inputs.name }} on ${{ inputs.os }}"
